server:
  port: 8017

dns-cfg:
  # 每天8:30执行         每隔1小时执行一次："0 0 */1 * * *"
  cron: "0 30 8 * * ?"
  # DNS服务器地址：谷歌：8.8.8.8、OpenDNS：208.67.222.222或208.67.220.220
  dns-server: 208.67.222.222
  proxy-domain: cdn-all.xn--b6gac.eu.org
  # 地址：https://www.maxmind.com 创建License Key ，将Account ID和License key拼接成 `Account ID:License key` 并用base64编码的结果
#  geoip-auth: OTc3MTUyOk9XZXlZRl9pR3BZYkszZkhmaEhnUmhrVFFNbVptVmYzcTU1b19tbWs=
  out-put-file: /app/proxyIps.txt

# cloudflare配置
cloudflare-cfg:
  zone-id: xx
  # 需要自行创建
  api-token: bb
  # root域名（cf托管的域名）
  root-domain: abc.com
  # 优选ip域名前缀
  proxy-domain-prefix: proxyip